Added CustomerService
MirazamTUT/OnlinePharmacyShopping pull request #17
Opened 2023-07-17 11:14 UTC by isfandiyoro5

Updated apsetting.json

2023-07-18 10:59 UTC, MirazamTUT requested changes

2023-07-18 10:59 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +        public async Task<int> DeleteCustomerAsync(CustomerRequestDTO customerRequestDTO, int id)
id ni o'zi qolishi kerak

2023-07-18 10:59 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                customerResult = _mapper.Map<Customer>(customerRequestDTO);
shunda bula keremas

2023-07-18 10:59 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                customerResult.CustomerId = id;
delete methodida id bo'yicha qidirib bor bo'lsa o'chiramz

2023-07-18 15:07 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                customerResult = _mapper.Map<Customer>(customerRequestDTO);
ok

2023-07-18 15:07 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                customerResult.CustomerId = id;
ok

2023-07-19 07:11 UTC, MirazamTUT requested changes

2023-07-19 07:11 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/ServiceExtentions/ServiceExtentions.cs
>              services.AddScoped<IPurchaseRepository, PurchaseRepository>();
mashetga PharmacyRepositoryni ham registratsiya qivoring yozilmagan ekan

2023-07-19 07:17 UTC, MirazamTUT approved these changes, later dismissed

2023-07-19 07:22 UTC, MirazamTUT approved these changes

2023-07-19 07:25 UTC, merged