28 exceptions for services
MirazamTUT/OnlinePharmacyShopping pull request #25
Opened 2023-07-20 10:15 UTC by qAziz060708

2023-07-21 09:03 UTC, MirazamTUT requested changes

2023-07-21 09:03 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +            catch (DbUpdateException ex)
mashnaqa exceptionlarga ex.messege qaytarsn

2023-07-22 07:08 UTC, MirazamTUT requested changes

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                throw new Exception("Connection between database is failed");
mashetta ex.message bo'lishi kerak edi

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +            }
betta ortiqcha joy bor }mashi qovusdan keyin

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +            }
betta ortiqcha joy bor }mashi qovusdan keyin

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +            }
betta ortiqcha joy bor }mashi qovusdan keyin

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/CustomerService.cs
> +                throw new Exception("Connection between database is failed");
ex.message bo'lishi kerak edi

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/MedicineService.cs
58-qatordagi catchda ex.message bo'lishi kerak edi

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/MedicineService.cs
>                  throw new Exception("Connection between database is failed");
betta ex.message bo'lishi kerak edi

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/PharmacyService.cs
> +                throw new Exception("Connection between database is failed");
Ex.message bo'lishi kerak

2023-07-22 07:08 UTC, MirazamTUT commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/PharmacyService.cs
> +                throw new Exception("Connection between database is failed");
ex.message bo'lishi kerak

2023-07-22 12:32 UTC, isfandiyoro5 requested changes

2023-07-22 12:32 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/Service/Services/PharmacyService.cs
> +                throw new Exception("Connection between database is failed");
Ex.Message qilishiz kk

2023-07-22 12:41 UTC, isfandiyoro5 submitted a review, later dismissed

2023-07-22 13:43 UTC, isfandiyoro5 approved these changes

2023-07-23 07:39 UTC, MirazamTUT approved these changes

2023-07-23 09:40 UTC, merged