53 create payment model
MirazamTUT/OnlinePharmacyShopping pull request #44
Opened 2023-08-08 17:43 UTC by qAziz060708

2023-08-10 07:10 UTC, isfandiyoro5 requested changes

2023-08-10 07:10 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/DTO/RequestDTOs/PaymentRequestDTO.cs
> +
line qoshilib qopti

2023-08-10 07:10 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/DTO/RequestDTOs/PaymentRequestDTO.cs
> +        public int SaleID { get; set; }
SaleID ni d sini kichkina qip qoying

2023-08-10 07:10 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.BusinessLogic/DTO/ResponseDTOs/PaymentResponseDTO.cs
> +        public int SaleID { get; set; }
buniyam d sini kichkina qilish kk

2023-08-10 07:10 UTC, isfandiyoro5 commented on OnlinePharmacyShopping/PharmacyShopping.DataAccess/Models/Payment.cs
> +        public int SaleID { get; set; }
d sini kichkina qilish kk

2023-08-13 19:30 UTC, qAziz060708 commented
I Fixed changes

2023-08-14 06:27 UTC, isfandiyoro5 approved these changes

2023-08-18 07:01 UTC, merged